openapi: 3.0.0
info:
  title: My API
  version: "1.0.0"
  description: API for user authentication and profile access

paths:
  /api/login:
    post:
      summary: User login
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        "401":
          description: Invalid credentials
  /api/logout:
    post:
      summary: User logout
      tags:
        - Authentication
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful logout

  /api/user:
    get:
      summary: Get user profile
      tags:
        - User
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          required: false
          description: News page number
          schema:
            type: integer
      responses:
        "200":
          description: User profile
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProfile"
        "401":
          description: Unauthorized

  /api/news:
    get:
      summary: Get all news
      tags:
        - News
      parameters:
        - name: page
          in: query
          required: false
          description: News page number
          schema:
            type: integer
      responses:
        "200":
          description: List of all news
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/News"

  /api/news/{id}:
    get:
      summary: Get a specific news article
      tags:
        - News
      parameters:
        - name: id
          in: path
          required: true
          description: News ID
          schema:
            type: integer
      responses:
        "200":
          description: News details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/News"
        "404":
          description: News not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    LoginRequest:
      type: object
      required:
        - email
        - password
        - device_name
      properties:
        email:
          type: string
          format: email
          example: test@example.com
        password:
          type: string
          format: password
          example: 123456
        device_name:
          type: string
          example: device_name

    LoginResponse:
      type: object
      properties:
        token:
          type: string
          example: eyJ0eXAiOiJKV1QiLCJhbGciOi...

    UserProfile:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: John Doe
        email:
          type: string
          example: john@example.com

    News:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: News Title
        description:
          type: string
          example: News Description
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
