openapi: 3.0.0
info:
  title: My API
  version: "1.0.0"
  description: API for user authentication and profile access

paths:
  /api/login:
    post:
      summary: User login
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        "401":
          description: Invalid credentials
  /api/logout:
    post:
      summary: User logout
      tags:
        - Authentication
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful logout

  /api/user:
    get:
      summary: Get user profile
      tags:
        - User
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          required: false
          description: News page number
          schema:
            type: integer
      responses:
        "200":
          description: User profile
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProfile"
        "401":
          description: Unauthorized

  /api/news:
    get:
      summary: Get all news
      tags:
        - News
      parameters:
        - name: page
          in: query
          required: false
          description: News page number
          schema:
            type: integer
      responses:
        "200":
          description: List of all news
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/News"

  /api/news/{id}:
    get:
      summary: Get a specific news article
      tags:
        - News
      parameters:
        - name: id
          in: path
          required: true
          description: News ID
          schema:
            type: integer
      responses:
        "200":
          description: News details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/News"
        "404":
          description: News not found

  /api/comments:
    get:
      summary: Get all comments
      tags:
        - Comments
      parameters:
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
            default: 1
        - name: per_page
          in: query
          description: Number of items per page
          required: false
          schema:
            type: integer
            default: 10
        - name: user_id
          in: query
          description: Filter comments by user ID
          required: false
          schema:
            type: integer
            example: 1
        - name: news_id
          in: query
          description: Filter comments by news ID
          required: false
          schema:
            type: integer
            example: 1
        - name: body
          in: query
          description: Filter comments by body text (partial match)
          required: false
          schema:
            type: string
            example: "comment text"
        - name: user_email
          in: query
          description: Filter comments by user email (partial match)
          required: false
          schema:
            type: string
            format: email
            example: "user@example.com"
        - name: from_date
          in: query
          description: Filter comments created after this date and time
          required: false
          schema:
            type: string
            format: date-time
            example: "2024-01-01T00:00:00Z"
        - name: to_date
          in: query
          description: Filter comments created before this date
          required: false
          schema:
            type: string
            format: date
            example: "2024-12-31"
      responses:
        "200":
          description: List of comments
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Comment"
                  links:
                    type: object
                    properties:
                      first:
                        type: string
                      last:
                        type: string
                      prev:
                        type: string
                      next:
                        type: string
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                      from:
                        type: integer
                      last_page:
                        type: integer
                      path:
                        type: string
                      per_page:
                        type: integer
                      to:
                        type: integer
                      total:
                        type: integer
    post:
      summary: Create a new comment
      tags:
        - Comments
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CommentRequest"
      responses:
        "201":
          description: Comment created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Comment"
        "401":
          description: Unauthorized
        "422":
          description: Validation error

  /api/comments/{id}:
    get:
      summary: Get a specific comment
      tags:
        - Comments
      parameters:
        - name: id
          in: path
          required: true
          description: Comment ID
          schema:
            type: integer
      responses:
        "200":
          description: Comment details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Comment"
        "404":
          description: Comment not found
    put:
      summary: Update a comment
      tags:
        - Comments
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: Comment ID
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CommentRequest"
      responses:
        "200":
          description: Comment updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Comment"
        "401":
          description: Unauthorized
        "404":
          description: Comment not found
        "422":
          description: Validation error
    delete:
      summary: Delete a comment
      tags:
        - Comments
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: Comment ID
          schema:
            type: integer
      responses:
        "200":
          description: Comment deleted successfully
        "401":
          description: Unauthorized
        "404":
          description: Comment not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    LoginRequest:
      type: object
      required:
        - email
        - password
        - device_name
      properties:
        email:
          type: string
          format: email
          example: test@example.com
        password:
          type: string
          format: password
          example: 123456
        device_name:
          type: string
          example: device_name

    LoginResponse:
      type: object
      properties:
        token:
          type: string
          example: eyJ0eXAiOiJKV1QiLCJhbGciOi...

    UserProfile:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: John Doe
        email:
          type: string
          example: john@example.com

    News:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: News Title
        description:
          type: string
          example: News Description
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Comment:
      type: object
      properties:
        id:
          type: integer
          example: 1
        body:
          type: string
          example: "This is a comment"
        user_id:
          type: integer
          example: 1
        news_id:
          type: integer
          example: 1
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        user:
          $ref: "#/components/schemas/User"

    CommentRequest:
      type: object
      required:
        - body
        - news_id
      properties:
        body:
          type: string
          example: "This is a new comment"
        news_id:
          type: integer
          example: 1

    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "John Doe"
        email:
          type: string
          format: email
          example: "john@example.com"
